config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :lists
  resources :items
  delete '/items/:id(.:format)' => 'items#destroy'
  post '/items/upvote/:id' => 'items#upvote', :as => :upvote
  post '/items/downvote/:id' => 'items#downvote', :as => :downvote

  get "mystuff" => 'static#mystuff'
  root to: 'static#homepage'
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_votable
  belongs_to :list
  belongs_to :user

  validates :title, presence: true
  validates :url, :url => {:allow_nil => true, :allow_blank=>true}


  default_scope { order('cached_votes_total DESC') }
  scope :latest, -> { order("created_at desc").limit(5) }
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user

  validates :title, presence: true
  validates :user_id, presence: true

  default_scope { order("created_at desc") }
  scope :latest, -> { limit(5) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  has_many :items
  has_many :lists
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/concerns/resource_inflections_concern.rb
module ResourceInflectionsConcern
  extend ActiveSupport::Concern

  included do
    helper_method :inflections
  end

  private

  def inflections
    {
      singular: resource_class.model_name.human(count: 1),
      plural: resource_class.model_name.human(count: 2)
    }
  end
end

app/controllers/concerns/resource_rest_actions_concern.rb
module ResourceRestActionsConcern
  extend ActiveSupport::Concern

  include ResourceUrlsConcern
  include ResourceInflectionsConcern

  included do
    respond_to :html

    helper_method :resource_class
    helper_method :query_class
  end

  def index
    @query = query_class.new(params)
    @collection = @query.scope(starting_scope)
    respond_with @collection
  end

  def new
    @resource = resource_class.new
    respond_with @resource
  end

  def create
    @resource = resource_class.new(permitted_params)
    @resource.save
    respond_with @resource, location: collection_url
  end

  def edit
    @resource = resource_class.find(params[:id])
    respond_with @resource
  end

  def update
    @resource = resource_class.find(params[:id])
    @resource.update_attributes(permitted_params)
    respond_with @resource, location: collection_url
  end

  def destroy
    @resource = resource_class.find(params[:id])
    @resource.destroy
    respond_with @resource, location: collection_url
  end

  protected

  def resource_class
    controller_name.classify.constantize
  end

  def query_class
    "#{controller_name.classify.pluralize}Query".constantize
  end
  
  def starting_scope
  end
end

app/controllers/concerns/resource_urls_concern.rb
module ResourceUrlsConcern
  extend ActiveSupport::Concern

  included do
    helper_method :edit_resource_url,
      :resource_url,
      :new_resource_url,
      :collection_url
  end

  private

  def edit_resource_url(resource)
    url_for(controller: controller_path, action: :edit, id: resource)
  end

  def resource_url(resource)
    url_for(controller: controller_path, action: :show, id: resource)
  end

  def new_resource_url
    url_for(controller: controller_path, action: :new)
  end

  def collection_url
    url_for(controller: controller_path, action: :index)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = Item.new
    if params[:list_id]
      @list = List.find(params[:list_id])
      @item.list = @list
    end
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    @item.save

    if @item.save
      flash[:notice] = "You have successfully create the item."
      redirect_to list_path(@item.list_id)
    else
      render 'new'
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    item = Item.find(params[:id])
    list = item.list_id
    item.destroy
    flash[:alert] = "You have successfully destroy the item."
    redirect_to list_path(list)
  end

  def upvote
    @item = Item.find(params[:id])
    if @item.present?
      @item.liked_by current_user
      redirect_to list_path(@item.list_id)
    end
  end
  def downvote
    @item = Item.find(params[:id])
    if @item.present?
      @item.unliked_by current_user
      redirect_to list_path(@item.list_id)
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :url, :list_id, :user_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    @list.save

    if @list.save
      flash[:notice] = "You have successfully create a new list."
      redirect_to @list
    else
      render 'new'
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end


  def destroy
    list = List.find(params[:id])
    if list.items.count == 0
      list.destroy
      flash[:alert] = "list destroyed"
      redirect_to lists_path()
    else
      flash[:alert] = "NO! Delete all items in the list in order to delete it."
      redirect_to list_path(list)
    end

  end




  private

  def list_params
    params.require(:list).permit(:title, :description)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!
  def homepage
    @lists = List.all.limit(5)
    @items = Item.all
  end

  def mystuff
    @lists = List.all.where("user_id = ?", current_user.id).order("created_at desc")
    @items = Item.all.where("user_id = ?", current_user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% flash.each do |key, value| -%>
  <div class="flash--<%= key %>"><%= value %></div>
<% end -%>

app/views/application/_items_list.html.slim
- not_in_list ||= false
.items-list
  table.table
    tbody
      - present_collection(items.sort_by(&:cached_votes_total).reverse).each do |item|
        tr.item
          td.item__votes data-title="votes"
            .alpha = item.get_likes.size
            - if not not_in_list.present?
              - if current_user.voted_for? item
                = form_tag(downvote_path({:id => item.id})) do
                  = submit_tag 'DOWN', class: "button--alert button--milli"
              - else
                = form_tag(upvote_path({:id => item.id})) do
                  = submit_tag 'UP', class: "button--primary button--milli"
            - else
              span votes

          td data-title=""
            .item__title = item.full_title
            .item__description = item.description
            .item__meta.milli
              =' item.meta
            - if not_in_list.present?
              .align--right
                = item.list_link

          td.item__actions data-title="actions"
            - if not not_in_list.present?
              - if item.user == current_user
                / = link_to "", edit_item_path(item), class: 'icon--check icon--large item__edit'

                = link_to "", item_path(item), method: :delete, class: 'icon--cross icon--large item__delete', data: { confirm: "Are you sure?" }

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_lists_list.html.slim
.items-list--lists
  table.table
    tbody
      - present_collection(lists).each do |item|
        tr.item
          td.item__votes data-title="votes"
            .alpha = item.items.count
            span items

          td data-title=""
            .item__title = item.full_title
            .item__description = item.description
            .item__meta.milli
              =' item.meta

app/views/items/index.html.slim
.formatted-content
  h1 Items index

  ul
    - @items.each do |item|
      li
        = link_to item.title, item_path(item)
        .milli = time_ago_in_words(item.created_at)

app/views/items/new.html.slim
- list = present(@list)

.formatted-content
  .space--both-2
    - if @list.present?
      h1 A new item in "#{@list.title}"'s list
      p.milli
        = list.meta
        ',
        = list.items_count
      = link_to "oh no! Back to list items", list_path(@list), class: "button--small"
    - else
      h2 New Item


= simple_form_for @item do |f|
  = f.input :title
  = f.input :description
  = f.input :url
  = f.association :list
  = f.button :submit

app/views/items/show.html.slim
.formatted-content
  h1 = @item.title
  p = @item.description

  - if @item.url
    = link_to @item.url, @item.url

  .milli
    = time_ago_in_words(@item.created_at)

app/views/layouts/application.html.slim
doctype 5
html
  head
    meta charset="utf-8"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1"
    meta name="mobile-web-app-capable" content="yes"
    = stylesheet_link_tag "application"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
    = csrf_meta_tags


  body
    = render "flashes"

    .site-header
      .wrap
        .gamma Majorette / upvote everything
        .nav--dots
          .nav__item = link_to "home", root_path
          .nav__item = link_to "browse lists", lists_path
          - if user_signed_in?
            .nav__item = link_to "my stuff", mystuff_path
            .nav__item = link_to "logout", destroy_user_session_path, :method => :delete
          - else
            .nav__item = link_to "login", new_user_session_path

      .space--both-2.align--center
        .nav
          .nav__item
            = link_to "create a list", new_list_path, class: "button--small"
          .nav__item
            = link_to "add an item", new_item_path, class: "button--small  button--primary"

    .wrap
      = yield
    = render "javascript"

app/views/lists/index.html.slim
.formatted-content
  h1 list index
  = render "lists_list", lists: @lists

app/views/lists/new.html.slim
.formatted-content
  h2 New list


= simple_form_for @list do |f|
  fieldset
    = f.input :title
    = f.input :description
    = f.button :submit

app/views/lists/show.html.slim
- list = present(@list)
h1.alpha = list.title
p.milli
  = list.meta
  ',
  = list.items_count

.space--both-2.align--center
  = link_to "add new item in #{@list.title}", new_item_path(list_id: @list.id), class: "button--primary"

- if @list.user.id == current_user.id && @list.items.count == 0
  = link_to "destroy list", list_path(@list.id), method: :delete, class: "button--small button--alert"

= render "items_list", items: @list.items